id = "swarm"
name = "Swarm Language"
version = "0.1.0"
schema_version = 1
authors = ["Roshan Padaki <roshanpadaki@gmail.com>"]
description = "Swarm ant colony language support (.sw files)"

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.swarm]
repository = "https://github.com/rpadaki/tree-sitter-swarm"
rev = "348e230b5901fe88805cfffc039fdd568c076451"

[language_servers.swarm-lsp]
language = "Swarm"
