id = "swarm"
name = "Swarm Language"
version = "0.1.0"
schema_version = 1
authors = ["Roshan Padaki <roshanpadaki@gmail.com>"]
description = "Swarm ant colony language support (.sw files)"

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.swarm]
repository = "https://github.com/rpadaki/tree-sitter-swarm"
rev = "612d47732c6d940ed36a6fcd7704bbf7545042e6"

[language_servers.swarm-lsp]
language = "Swarm"
