id = "swarm"
name = "Swarm Language"
version = "0.1.0"
schema_version = 1
authors = ["Roshan Padaki <roshanpadaki@gmail.com>"]
description = "Swarm ant colony language support (.sw files)"

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.swarm]
repository = "https://github.com/rpadaki/tree-sitter-swarm"
rev = "b0475071b162d1ce47a5dd182e52f10ae3e84bba"

[language_servers.swarm-lsp]
language = "Swarm"
